version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        expose:
            - '3306'
        env_file:
            - .env
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - inception
        tty: true

    wordpress:
        depends_on:
            - mariadb
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        expose:
            - '9000'
        volumes:
            - wordpress-data:/var/www/html
        networks:
            - inception

    nginx:
        depends_on:
            - wordpress
        container_name: ngnix
        build: ./requirements/nginx
        restart: always
        ports:
            - '443:443'
        volumes:
            - wordpress-data:/var/www/html/wordpress
        networks:
            - inception

volumes:	
    mariadb-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/min/data/mysql
    wordpress-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/min/data/wordpress
networks:
    inception:
        driver: bridge
